version: '3.7'

services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./src/
      dockerfile: Dockerfile
    image: robot
    container_name: app-robot
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-robot
    restart: unless-stopped
    ports:
      - '2002:80'
    volumes:
      - ./src/:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
