version: "3"
services:
  blog_app:
    build:
      context: . # The path of the Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: blog-app
    networks:
      - app_network

  blog_nginx:
    build:
      context: ./docker-nginx/. # The path of the Dockerfile
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: blog_app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "2002:80"
    depends_on:
      - blog_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
